version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm
      - run:
          name: Update yarn
          command: npm update -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Tests with coverage
          command: yarn jest --coverage
      - store_artifacts:
          path: coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
